### PR TITLE
jk -- add optional file prefix string …

### PR DESCRIPTION
**Pull request by berkeleysquare**
to be prepended in Bulk Get or Bulk Put (NETSDK -2)

### CODE REVIEW

**Comment by rpmoore** [comment]
Please add unit tests for this commit.

**Comment by berkeleysquare** [comment]
I wondered about that.  These tend to operate on the filesystem.

Can I expect to be able to write to C:\tmp in the test?

jk

**Comment by rpmoore** [comment]
I would create a temp dir using the system call so that it doesn't matter what system we're on.

**Comment by berkeleysquare** [comment]
Poorly worded, but that is what I meant. This need .NET so I can assume it always runs on a platform that supports that?

Some good news – while testing, I was able to reproduce the defect I closed as non-reproducible.  If you call ListObjectsForDirectory() with a trailing slash on the directory, it counts to the length and truncates the first char.

jk

**Comment by rpmoore** [comment]
It looks like there might be a pathing issue in the new prefix test.  It fails due to this:

 System.IO.DirectoryNotFoundException : Directory '/tmp/testprefix\src' not found.

**Comment by berkeleysquare** [comment]
That was actually what I was worried about. It works on mine, but where this is running, it looks like Path.GetTempDirectory() returns /tmp/ I concatenate tesprefix\src and that is not a valid address where the test is running.

Where is this running that it fails? Anybody I can talk to?

jk

**Comment by berkeleysquare** [comment]
I wonder about the unix vs. DOS slash. Is there a way I can run this on the test machine?

jk

**Pull request merged**
